language: node_js
services:
  - redis-server
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.7"
script:
  - ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter > coverage.out
after_script:
  - ./node_modules/.bin/coveralls < coverage.out
